language: node_js
node_js:
- node
before_script:
- cd functions && yarn && cd ..
script:
- yarn run test:unit
- yarn build
before_install:
- export TZ=Asia/Shanghai
- date
cache:
  yarn: true
deploy:
  provider: firebase
  token:
    secure: Uql4116u4iIo8UhuEa989U6goj1JLuQJr+W2+iOnvG2+t1RANtoXymcIiWLHEEzdsAUapWzu8m2owAAXenHyPUtsittekLBMm9mA7VVHQyE/U22wZqwYY8UM1D96Gepw+C7cqfugm+WeEZt9OaszlKmNPOSBL4dbUPGO77SNjs6BBAOE2l3mOP8NjVao3o85AJAc48lUJzXO2HMgP3yv2Vsrm5x1DgE371y+UBtNuV3kbg041nYVExMC6PgyUbmoSW+SVwf2Gv3lVKR9O+kVHIqYIDlzVcruNm08B3JyayeYJDI6Qx6CQo6uC3PDLxxvsbtPGDDG1l8hwtA9BZYemavVIxdRuhvKGWiJNHNZpcgzR1OxiT54oXcAE+bfdp4VMHJzc1EJPJqQz4dtykOdvuEBCAcLu8pC6rcQDIgLFmodXOZCz5+5osjBs8eHejvn0sJX+70QIJLF3ud2IettQdNArlUsO0YjMe0dlR4X3UENSaHceGqcNgnkJav3vcCFHpWVL6p+Ri1hqBJ+BUi1Nk6xSzlq/XHOoYSuZtvE7U94eyYddlWX3vxl2VquDwJDDY826sp00051yVntyEA9UxQaA3MsV6GpN/DoMxNroddSiaSoZRo/XQd/hKMDnY9EzAlNo81fELwfGDUjeT5Stq2v67h5a07h284F24XTG0E=
  message: Deployed via Travis CI
  skip_cleanup: true
