language: node_js
node_js:
  - 'node' # use latest stable nodejs version
script:
  - yarn run test:unit # jest test with coverage flag does coverage too
  - yarn run build
before_install:
  - export TZ=Asia/Shanghai
  - date
cache:
  yarn: true
  directories:
  - node_modules